import { worldToPct } from './utils.js';

// ─── EXTRACT DATA (with approx. map positions + item requirements) ────────
export const EMAPS = [
  {id:"customs",name:"Customs",tier:"Beginner",diff:1,color:"#c8a84b",
   desc:"Best starting map. Dense early quests.",bosses:["Reshala + 4 guards (Dorms)"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Customs",mapgenie:"https://mapgenie.io/tarkov/maps/customs",tarkovdev:"https://tarkov.dev/map/customs",
   lootPoints:[
    {name:"Marked Room (Dorms 314)",type:"high-value",pct:{x:0.47,y:0.93},note:"Rare loot room — requires Marked Key",tags:["Weapon","Info","Key","Jewelry","Electronics"]},
    {name:"3-Story Dorms",type:"mixed",pct:{x:0.48,y:0.94},note:"Multiple locked rooms, weapon crates, jackets",tags:["Weapon","Weapon mod","Key","Jewelry","Meds","Info"]},
    {name:"2-Story Dorms",type:"mixed",pct:{x:0.50,y:0.92},note:"Safes, weapon boxes, quest items",tags:["Jewelry","Money","Weapon","Info"]},
    {name:"Crack House",type:"mixed",pct:{x:0.52,y:0.62},note:"Medical supplies, weapon parts, tech spawns",tags:["Meds","Medical supplies","Weapon mod","Electronics"]},
    {name:"USEC Stash (Big Red)",type:"tech",pct:{x:0.92,y:0.20},note:"Intel spawns, electronics, valuables",tags:["Electronics","Info","Jewelry"]},
    {name:"New Gas Station",type:"mixed",pct:{x:0.56,y:0.50},note:"Medical crate, food, barter items",tags:["Meds","Food","Barter item","Medical supplies"]},
    {name:"Old Gas Station",type:"stash",pct:{x:0.36,y:0.24},note:"Duffle bags, hidden stashes nearby",tags:["Barter item","Building material","Tool","Food"]},
    {name:"Warehouse 4 (Factory Shacks)",type:"mixed",pct:{x:0.40,y:0.55},note:"Weapon crates, loose loot, jackets",tags:["Weapon","Weapon mod","Ammo","Barter item"]},
   ],
   pmcExtracts:[
    {name:"Crossroads",                type:"open",   note:"Always available — south side", pct:{x:0.97,y:0.40}, requireItems:[]},
    {name:"RUAF Roadblock",            type:"open",   note:"Always available — central", pct:{x:0.66,y:0.31}, requireItems:[]},
    {name:"Trailer Park",              type:"open",   note:"Always available — far west", pct:{x:0.95,y:0.14}, requireItems:[]},
    {name:"Smugglers' Boat",           type:"open",   note:"Always available — south riverbank", pct:{x:0.69,y:0.79}, requireItems:[]},
    {name:"Old Gas Station",           type:"open",   note:"Always available", pct:{x:0.36,y:0.24}, requireItems:[]},
    {name:"Dorms V-Ex",                type:"pay",    note:"Pay roubles — 3-story dorms parking", pct:{x:0.48,y:0.96}, requireItems:["Roubles"]},
    {name:"ZB-1011",                   type:"key",    note:"Requires ZB-1011 key", pct:{x:0.07,y:0.33}, requireItems:["ZB-1011 key"]},
    {name:"Smugglers' Bunker (ZB-1012)", type:"key",  note:"Requires key", pct:{x:0.22,y:0.36}, requireItems:["ZB-1012 key"]},
    {name:"ZB-013",                    type:"key",    note:"Requires ZB-013 key", pct:{x:0.46,y:0.28}, requireItems:["ZB-013 key"]},
    {name:"Railroad Passage (Flare)",  type:"special",note:"Requires flare", pct:{x:0.52,y:0.02}, requireItems:["Flare"]},
    {name:"Boiler Room Basement (Co-op)", type:"coop", note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
   scavExtracts:[
    {name:"Crossroads",                type:"open",   note:"Always available", pct:{x:0.97,y:0.40}, requireItems:[]},
    {name:"Military Base CP",          type:"open",   note:"Always available", pct:{x:0.05,y:0.80}, requireItems:[]},
    {name:"Passage Between Rocks",     type:"open",   note:"Always available", pct:{x:0.15,y:0.93}, requireItems:[]},
    {name:"Railroad to Military Base", type:"open",   note:"Always available", pct:{x:0.20,y:0.97}, requireItems:[]},
    {name:"Old Road Gate",             type:"open",   note:"Always available", pct:{x:0.48,y:0.96}, requireItems:[]},
    {name:"Sniper Roadblock",          type:"open",   note:"Always available", pct:{x:0.64,y:0.80}, requireItems:[]},
    {name:"Railroad to Port",          type:"open",   note:"Always available", pct:{x:0.79,y:0.65}, requireItems:[]},
    {name:"Trailer Park Workers' Shack", type:"open", note:"Always available", pct:{x:0.88,y:0.14}, requireItems:[]},
    {name:"Railroad to Tarkov",        type:"open",   note:"Always available", pct:{x:0.81,y:0.16}, requireItems:[]},
    {name:"RUAF Roadblock",            type:"open",   note:"Always available", pct:{x:0.66,y:0.31}, requireItems:[]},
    {name:"Warehouse 17",              type:"open",   note:"Always available", pct:{x:0.60,y:0.44}, requireItems:[]},
    {name:"Factory Shacks",            type:"open",   note:"Always available", pct:{x:0.46,y:0.57}, requireItems:[]},
    {name:"Warehouse 4",               type:"open",   note:"Always available", pct:{x:0.33,y:0.52}, requireItems:[]},
    {name:"Old Gas Station Gate",      type:"open",   note:"Always available", pct:{x:0.37,y:0.20}, requireItems:[]},
    {name:"Factory Far Corner",        type:"open",   note:"Always available", pct:{x:0.04,y:0.27}, requireItems:[]},
    {name:"Administration Gate",       type:"open",   note:"Always available", pct:{x:0.03,y:0.46}, requireItems:[]},
    {name:"Scav Checkpoint",           type:"coop",   note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
  },
  {id:"factory",name:"Factory",tier:"Beginner",diff:1,color:"#a85c3a",
   desc:"Tiny arena. Great for kill quests.",bosses:["Tagilla (avoid early)"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Factory",mapgenie:"https://mapgenie.io/tarkov/maps/factory",tarkovdev:"https://tarkov.dev/map/factory",
   lootPoints:[
    {name:"Office (3rd Floor)",type:"mixed",pct:{x:0.6,y:0.25},note:"Safe, PC, jackets — best loot in Factory",tags:["Jewelry","Money","Electronics","Info","Key"]},
    {name:"Pumping Station",type:"mixed",pct:{x:0.35,y:0.5},note:"Weapon crates, loose ammo",tags:["Weapon","Weapon mod","Ammo"]},
    {name:"Breach Room",type:"mixed",pct:{x:0.5,y:0.7},note:"Weapon parts, medical spawns",tags:["Weapon mod","Meds","Medical supplies"]},
    {name:"Locker Room",type:"stash",pct:{x:0.7,y:0.55},note:"Jackets, duffle bags",tags:["Key","Barter item","Money"]},
   ],
   pmcExtracts:[
    {name:"Gate 0",             type:"open",   note:"Always available", pct:{x:0.09,y:0.98}, requireItems:[]},
    {name:"Gate 3",             type:"open",   note:"Always available", pct:{x:0.03,y:0.13}, requireItems:[]},
    {name:"Cellars",            type:"open",   note:"Always available — basement exit", pct:{x:0.73,y:0.02}, requireItems:[]},
    {name:"Courtyard Gate",     type:"open",   note:"Always available", pct:{x:0.02,y:0.37}, requireItems:[]},
    {name:"Med Tent Gate",      type:"open",   note:"Always available", pct:{x:0.98,y:0.66}, requireItems:[]},
    {name:"Smugglers' Passage", type:"key",    note:"Requires key", pct:{x:0.73,y:0.20}, requireItems:["Factory key"]},
   ],
   scavExtracts:[
    {name:"Gate 3",             type:"open",   note:"Always available", pct:{x:0.05,y:0.13}, requireItems:[]},
    {name:"Camera Bunker Door", type:"open",   note:"Always available", pct:{x:0.21,y:0.65}, requireItems:[]},
    {name:"Office Window",      type:"open",   note:"Always available — 3rd floor", pct:{x:0.21,y:0.42}, requireItems:[]},
   ],
  },
  {id:"woods",name:"Woods",tier:"Beginner",diff:2,color:"#4a7c3f",
   desc:"Open terrain. Teaches positioning vs AI.",bosses:["Shturman + 2 guards (Sawmill)"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Woods",mapgenie:"https://mapgenie.io/tarkov/maps/woods",tarkovdev:"https://tarkov.dev/map/woods",
   lootPoints:[
    {name:"USEC Camp",type:"high-value",pct:{x:0.7,y:0.35},note:"Intel, electronics, weapon attachments, food",tags:["Info","Electronics","Weapon mod","Food","Barter item"]},
    {name:"Sunken Village",type:"mixed",pct:{x:0.25,y:0.65},note:"Hidden stashes, duffle bags, loose loot",tags:["Barter item","Building material","Tool","Food"]},
    {name:"Sawmill (Shturman)",type:"high-value",pct:{x:0.45,y:0.5},note:"Boss loot, weapon crates — dangerous area",tags:["Weapon","Weapon mod","Key","Ammo"]},
    {name:"Scav Bunker (ZB-016)",type:"mixed",pct:{x:0.6,y:0.44},note:"Weapon box, medical supplies",tags:["Weapon","Weapon mod","Meds","Medical supplies"]},
    {name:"Abandoned Village",type:"stash",pct:{x:0.35,y:0.78},note:"Stashes, jackets, food spawns",tags:["Food","Barter item","Key","Building material"]},
    {name:"Mountain Stash",type:"stash",pct:{x:0.78,y:0.15},note:"Hidden stashes along the ridge",tags:["Barter item","Building material","Tool","Meds"]},
   ],
   pmcExtracts:[
    {name:"UN Roadblock",              type:"open",   note:"Always available", pct:{x:0.84,y:0.89}, requireItems:[]},
    {name:"Northern UN Roadblock",     type:"open",   note:"Always available", pct:{x:0.86,y:0.62}, requireItems:[]},
    {name:"Outskirts",                 type:"open",   note:"Always available — far west", pct:{x:0.21,y:0.94}, requireItems:[]},
    {name:"RUAF Gate",                 type:"open",   note:"Always available", pct:{x:0.56,y:0.98}, requireItems:[]},
    {name:"Railway Bridge to Tarkov",  type:"open",   note:"Always available", pct:{x:0.98,y:0.77}, requireItems:[]},
    {name:"ZB-014",                    type:"key",    note:"Requires key", pct:{x:0.14,y:0.72}, requireItems:["ZB-014 key"]},
    {name:"ZB-016",                    type:"key",    note:"Requires key", pct:{x:0.74,y:0.68}, requireItems:["ZB-016 key"]},
    {name:"Bridge V-Ex",               type:"pay",    note:"Pay roubles", pct:{x:0.80,y:0.30}, requireItems:["Roubles"]},
    {name:"Power Line Passage (Flare)",type:"special",note:"Requires flare", pct:{x:0.05,y:0.61}, requireItems:["Flare"]},
    {name:"Friendship Bridge (Co-Op)", type:"coop",   note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
   scavExtracts:[
    {name:"Outskirts",          type:"open",   note:"Always available", pct:{x:0.21,y:0.94}, requireItems:[]},
    {name:"Dead Man's Place",   type:"open",   note:"Always available", pct:{x:0.32,y:0.87}, requireItems:[]},
    {name:"Boat",               type:"open",   note:"Always available", pct:{x:0.33,y:0.83}, requireItems:[]},
    {name:"Scav House",         type:"open",   note:"Always available", pct:{x:0.17,y:0.85}, requireItems:[]},
    {name:"Scav Bunker",        type:"open",   note:"Always available", pct:{x:0.30,y:0.15}, requireItems:[]},
    {name:"Mountain Stash",     type:"open",   note:"Always available", pct:{x:0.61,y:0.52}, requireItems:[]},
    {name:"Eastern Rocks",      type:"open",   note:"Always available", pct:{x:0.82,y:0.65}, requireItems:[]},
    {name:"Old Railway Depot",  type:"open",   note:"Always available", pct:{x:0.83,y:0.78}, requireItems:[]},
    {name:"UN Roadblock",       type:"open",   note:"Always available", pct:{x:0.84,y:0.89}, requireItems:[]},
    {name:"RUAF Roadblock",     type:"open",   note:"Always available", pct:{x:0.56,y:0.98}, requireItems:[]},
   ],
  },
  {id:"interchange",name:"Interchange",tier:"Intermediate",diff:2,color:"#3a6b8a",
   desc:"ULTRA Mall. High loot density.",bosses:["Killa (mall interior)"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Interchange",mapgenie:"https://mapgenie.io/tarkov/maps/interchange",tarkovdev:"https://tarkov.dev/map/interchange",
   lootPoints:[
    {name:"Techlight",type:"tech",pct:{x:0.59,y:0.27},note:"GPUs, Tetriz, electronics — top-tier tech loot",tags:["Electronics","Info"]},
    {name:"Rasmussen",type:"tech",pct:{x:0.59,y:0.38},note:"Electronics, barter items, tech spawns",tags:["Electronics","Barter item"]},
    {name:"KIBA Store",type:"high-value",pct:{x:0.59,y:0.47},note:"Weapons, attachments — requires 2 KIBA keys",tags:["Weapon","Weapon mod","Ammo"]},
    {name:"Goshan (grocery store)",type:"mixed",pct:{x:0.64,y:0.37},note:"Food, drinks, rations — best food loot on Interchange",tags:["Food","Food and drink","Drink","Barter item"]},
    {name:"OLI (back shelves)",type:"mixed",pct:{x:0.52,y:0.66},note:"Fuel, motors, hoses, hideout materials",tags:["Fuel","Building material","Tool","Household goods"]},
    {name:"IDEA Office",type:"mixed",pct:{x:0.58,y:0.20},note:"PCs, filing cabinets, office loot",tags:["Electronics","Info","Barter item"]},
    {name:"EMERCOM Medical",type:"medical",pct:{x:0.78,y:0.75},note:"Medical supplies, stims, LEDX chance",tags:["Meds","Medical supplies","Stimulant"]},
    {name:"Power Station",type:"stash",pct:{x:0.78,y:0.11},note:"Weapon box, toolboxes, loose loot",tags:["Weapon","Tool","Building material"]},
    {name:"Mantis / German",type:"mixed",pct:{x:0.56,y:0.49},note:"Weapon parts, barter items in mall center",tags:["Weapon mod","Barter item","Armor"]},
   ],
   pmcExtracts:[
    {name:"Emercom Checkpoint",  type:"open",   note:"Always available", pct:{x:0.89,y:0.82}, requireItems:[]},
    {name:"Railway Exfil",       type:"open",   note:"Always available", pct:{x:0.12,y:0.02}, requireItems:[]},
    {name:"Hole in the Fence",   type:"open",   note:"Always available — IDEA side", pct:{x:0.79,y:0.47}, requireItems:[]},
    {name:"Power Station V-Ex",  type:"pay",    note:"Pay roubles", pct:{x:0.82,y:0.09}, requireItems:["Roubles"]},
    {name:"Saferoom Exfil",      type:"key",    note:"Requires key + power on", pct:{x:0.63,y:0.56}, requireItems:["Saferoom key"]},
    {name:"Scav Camp (Co-Op)",   type:"coop",   note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
   scavExtracts:[
    {name:"Emercom Checkpoint",  type:"open",   note:"Always available", pct:{x:0.89,y:0.82}, requireItems:[]},
    {name:"Railway Exfil",       type:"open",   note:"Always available", pct:{x:0.12,y:0.02}, requireItems:[]},
    {name:"Scav Camp (Co-Op)",   type:"coop",   note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
  },
  {id:"shoreline",name:"Shoreline",tier:"Intermediate",diff:3,color:"#5a8a7a",
   desc:"Resort = high risk/reward zone.",bosses:["Sanitar + guards (Resort)"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Shoreline",mapgenie:"https://mapgenie.io/tarkov/maps/shoreline",tarkovdev:"https://tarkov.dev/map/shoreline",
   lootPoints:[
    {name:"East Wing Resort",type:"high-value",pct:{x:0.55,y:0.25},note:"LEDX, GPUs, rare keys — many locked rooms",tags:["Medical supplies","Electronics","Key","Jewelry","Stimulant"]},
    {name:"West Wing Resort",type:"high-value",pct:{x:0.48,y:0.25},note:"Safes, weapon spawns, intel folders",tags:["Jewelry","Money","Weapon","Info","Key"]},
    {name:"Admin Building (Resort)",type:"mixed",pct:{x:0.52,y:0.28},note:"PCs, office loot, quest items",tags:["Electronics","Info","Barter item"]},
    {name:"Pier",type:"mixed",pct:{x:0.52,y:0.85},note:"Safe, PCs, food, jackets",tags:["Jewelry","Money","Electronics","Food","Key"]},
    {name:"Gas Station",type:"mixed",pct:{x:0.62,y:0.55},note:"Medical crate, register, loose loot",tags:["Meds","Medical supplies","Food","Barter item"]},
    {name:"Weather Station",type:"tech",pct:{x:0.72,y:0.38},note:"Tech spawns, intel, electronics",tags:["Electronics","Info"]},
    {name:"Swamp Village",type:"stash",pct:{x:0.2,y:0.7},note:"Hidden stashes, tool boxes, building loot",tags:["Building material","Tool","Barter item"]},
   ],
   pmcExtracts:[
    {name:"Road to Customs",       type:"open",   note:"Always available", pct:{x:0.87,y:0.40}, requireItems:[]},
    {name:"Pier Boat",             type:"open",   note:"Always available", pct:{x:0.54,y:0.95}, requireItems:[]},
    {name:"Climber's Trail",       type:"special",note:"Requires Paracord + Red Rebel + no armored rig", pct:{x:0.46,y:0.05}, requireItems:["Paracord","Red Rebel Ice Pick"]},
    {name:"Path to Lighthouse",    type:"open",   note:"Always available", pct:{x:0.04,y:0.16}, requireItems:[]},
    {name:"Mountain Bunker",       type:"key",    note:"Requires key", pct:{x:0.57,y:0.03}, requireItems:["Bunker key"]},
    {name:"Railway Bridge",        type:"open",   note:"Always available", pct:{x:0.98,y:0.70}, requireItems:[]},
    {name:"Tunnel",                type:"open",   note:"Always available — west side", pct:{x:0.08,y:0.71}, requireItems:[]},
    {name:"Road to North V-Ex",    type:"pay",    note:"Pay roubles", pct:{x:0.67,y:0.03}, requireItems:["Roubles"]},
    {name:"Smugglers' Path (Co-op)", type:"coop", note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
   scavExtracts:[
    {name:"Road to Customs",       type:"open",   note:"Always available", pct:{x:0.87,y:0.40}, requireItems:[]},
    {name:"Lighthouse",            type:"open",   note:"Always available", pct:{x:0.62,y:0.95}, requireItems:[]},
    {name:"Ruined Road",           type:"open",   note:"Always available", pct:{x:0.09,y:0.72}, requireItems:[]},
    {name:"East Wing Gym Entrance",type:"open",   note:"Always available — Resort east wing", pct:{x:0.51,y:0.30}, requireItems:[]},
    {name:"Admin Basement",        type:"open",   note:"Always available — Resort basement", pct:{x:0.49,y:0.26}, requireItems:[]},
   ],
  },
  {id:"reserve",name:"Reserve",tier:"Advanced",diff:4,color:"#7a5a8a",
   desc:"Raiders are elite AI. Very dangerous.",bosses:["Glukhar (Admin)","Raiders (underground)"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Reserve",mapgenie:"https://mapgenie.io/tarkov/maps/reserve",tarkovdev:"https://tarkov.dev/map/reserve",
   lootPoints:[
    {name:"Marked Room (RB-BK)",type:"high-value",pct:{x:0.42,y:0.35},note:"Rare items, keycards, weapon cases",tags:["Weapon","Key","Keycard","Jewelry","Info"]},
    {name:"Black Knight",type:"mixed",pct:{x:0.55,y:0.42},note:"Weapon crates, attachments, ammo",tags:["Weapon","Weapon mod","Ammo"]},
    {name:"White Knight",type:"mixed",pct:{x:0.48,y:0.45},note:"Weapon spawns, crates, medical loot",tags:["Weapon","Weapon mod","Meds","Medical supplies"]},
    {name:"King Building",type:"high-value",pct:{x:0.52,y:0.38},note:"Intel, electronics, military tech",tags:["Info","Electronics","Weapon mod"]},
    {name:"Underground Bunkers",type:"high-value",pct:{x:0.4,y:0.55},note:"Raiders, weapon crates, ammo, rare spawns",tags:["Weapon","Ammo","Armor","Weapon mod","Meds"]},
    {name:"Helicopter",type:"mixed",pct:{x:0.58,y:0.5},note:"Military loot, weapon parts",tags:["Weapon mod","Ammo","Weapon"]},
    {name:"Drop-Down Room",type:"tech",pct:{x:0.35,y:0.3},note:"Tech spawns, loose electronics",tags:["Electronics","Info"]},
   ],
   pmcExtracts:[
    {name:"Cliff Descent",         type:"special",note:"Requires Paracord + Red Rebel + no armored rig", pct:{x:0.50,y:0.93}, requireItems:["Paracord","Red Rebel Ice Pick"]},
    {name:"D-2",                   type:"special",note:"Requires pulling levers in underground", pct:{x:0.69,y:0.87}, requireItems:[]},
    {name:"Exit to Woods",         type:"open",   note:"Always available", pct:{x:0.43,y:0.13}, requireItems:[]},
    {name:"Armored Train",         type:"timed",  note:"Spawns randomly — listen for the horn", pct:{x:0.24,y:0.27}, requireItems:[]},
    {name:"Bunker Hermetic Door",  type:"special",note:"Requires activation", pct:{x:0.38,y:0.19}, requireItems:[]},
    {name:"Sewer Manhole",         type:"open",   note:"Always available — no backpack allowed", pct:{x:0.42,y:0.69}, requireItems:[]},
    {name:"Scav Lands (Co-Op)",    type:"coop",   note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
   scavExtracts:[
    {name:"Hole in the Wall by the Mountains", type:"open", note:"Always available", pct:{x:0.93,y:0.64}, requireItems:[]},
    {name:"Heating Pipe",          type:"open",   note:"Always available", pct:{x:0.55,y:0.21}, requireItems:[]},
    {name:"Depot Hermetic Door",   type:"open",   note:"Always available", pct:{x:0.28,y:0.32}, requireItems:[]},
    {name:"Checkpoint Fence",      type:"open",   note:"Always available", pct:{x:0.38,y:0.80}, requireItems:[]},
   ],
  },
  {id:"lighthouse",name:"Lighthouse",tier:"Advanced",diff:4,color:"#8a7a3a",
   desc:"Rogues shoot PMCs on sight.",bosses:["Rogues (Water Treatment)","Zryachiy (island)"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Lighthouse",mapgenie:"https://mapgenie.io/tarkov/maps/lighthouse",tarkovdev:"https://tarkov.dev/map/lighthouse",
   lootPoints:[
    {name:"Water Treatment (Rogues)",type:"high-value",pct:{x:0.35,y:0.4},note:"Best loot on map — Rogue gear, crates, intel. Very dangerous.",tags:["Weapon","Armor","Weapon mod","Ammo","Electronics","Info"]},
    {name:"Chalet",type:"high-value",pct:{x:0.7,y:0.55},note:"Safes, valuables, rare spawns",tags:["Jewelry","Money","Info","Key"]},
    {name:"Resort Hotel",type:"mixed",pct:{x:0.55,y:0.65},note:"Safes, PCs, jackets, loose valuables",tags:["Jewelry","Money","Electronics","Key"]},
    {name:"Train Yard",type:"mixed",pct:{x:0.2,y:0.82},note:"Weapon crates, ammo spawns",tags:["Weapon","Weapon mod","Ammo"]},
    {name:"Rogue Camp (North)",type:"high-value",pct:{x:0.3,y:0.2},note:"Military crates, Rogue drops",tags:["Weapon","Armor","Weapon mod","Ammo"]},
    {name:"Southern Road Stashes",type:"stash",pct:{x:0.65,y:0.88},note:"Hidden stashes along the road",tags:["Barter item","Building material","Food","Meds"]},
   ],
   pmcExtracts:[
    {name:"Mountain Pass",             type:"special",note:"Requires Paracord + Red Rebel + no armored rig", pct:{x:0.65,y:0.58}, requireItems:["Paracord","Red Rebel Ice Pick"]},
    {name:"Northern Checkpoint",       type:"open",   note:"Always available", pct:{x:0.38,y:0.02}, requireItems:[]},
    {name:"Passage by the Lake",       type:"open",   note:"Always available", pct:{x:0.83,y:0.25}, requireItems:[]},
    {name:"Path to Shoreline",         type:"open",   note:"Always available", pct:{x:0.83,y:0.51}, requireItems:[]},
    {name:"Southern Road",             type:"open",   note:"Always available", pct:{x:0.76,y:0.82}, requireItems:[]},
    {name:"Road to Military Base V-Ex",type:"pay",    note:"Pay roubles", pct:{x:0.80,y:0.12}, requireItems:["Roubles"]},
    {name:"Armored Train",             type:"timed",  note:"Spawns randomly — listen for horn", pct:{x:0.48,y:0.07}, requireItems:[]},
    {name:"Side Tunnel (Co-Op)",       type:"coop",   note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
   scavExtracts:[
    {name:"Path to Shoreline",         type:"open",   note:"Always available", pct:{x:0.83,y:0.51}, requireItems:[]},
    {name:"Southern Road Landslide",   type:"open",   note:"Always available", pct:{x:0.75,y:0.82}, requireItems:[]},
    {name:"Hideout Under the Landing Stage", type:"open", note:"Always available", pct:{x:0.36,y:0.75}, requireItems:[]},
    {name:"Scav Hideout at the Grotto",type:"open",   note:"Always available", pct:{x:0.32,y:0.30}, requireItems:[]},
    {name:"Industrial Zone Gates",     type:"open",   note:"Always available", pct:{x:0.63,y:0.12}, requireItems:[]},
   ],
  },
  {id:"streets-of-tarkov",name:"Streets",tier:"Advanced",diff:4,color:"#8a4a4a",
   desc:"Massive urban map. The Goons roam here.",bosses:["The Goons (roaming)","Kolontay + guards"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Streets_of_Tarkov",mapgenie:"https://mapgenie.io/tarkov/maps/streets-of-tarkov",tarkovdev:"https://tarkov.dev/map/streets-of-tarkov",
   lootPoints:[
    {name:"Concordia",type:"high-value",pct:{x:0.45,y:0.4},note:"Apartments — safes, PCs, valuables, quest items",tags:["Jewelry","Money","Electronics","Info","Key"]},
    {name:"Lexos Dealership",type:"high-value",pct:{x:0.55,y:0.55},note:"High-value car spawns, intel, electronics",tags:["Info","Electronics","Jewelry"]},
    {name:"TerraGroup Building",type:"tech",pct:{x:0.38,y:0.6},note:"Tech loot, PCs, server racks",tags:["Electronics","Info"]},
    {name:"Cardinal Hotel",type:"mixed",pct:{x:0.85,y:0.18},note:"Multiple floors, weapon spawns, safes",tags:["Weapon","Jewelry","Money","Key","Meds"]},
    {name:"Pinewood Hotel",type:"mixed",pct:{x:0.3,y:0.3},note:"Safes, loose loot, jackets",tags:["Jewelry","Money","Key","Barter item"]},
    {name:"Sparja / Tarkone Shops",type:"mixed",pct:{x:0.62,y:0.42},note:"Grocery and convenience stores — food, drinks, rations",tags:["Food","Food and drink","Drink","Barter item","Meds"]},
    {name:"Underground Parking",type:"stash",pct:{x:0.5,y:0.7},note:"Weapon crates, duffle bags, stashes",tags:["Weapon","Barter item","Building material","Tool"]},
   ],
   pmcExtracts:[
    {name:"Courtyard",              type:"open",   note:"Always available", pct:{x:0.78,y:0.96}, requireItems:[]},
    {name:"Damaged House",          type:"open",   note:"Always available", pct:{x:0.95,y:0.77}, requireItems:[]},
    {name:"Crash Site",             type:"open",   note:"Always available", pct:{x:0.02,y:0.85}, requireItems:[]},
    {name:"Sewer River",            type:"open",   note:"Always available — underground sewer exit", pct:{x:0.98,y:0.62}, requireItems:[]},
    {name:"Collapsed Crane",        type:"open",   note:"Always available", pct:{x:0.18,y:0.69}, requireItems:[]},
    {name:"Expo Checkpoint",        type:"open",   note:"Always available", pct:{x:0.18,y:0.23}, requireItems:[]},
    {name:"Smugglers' Basement",    type:"open",   note:"Always available", pct:{x:0.41,y:0.42}, requireItems:[]},
    {name:"Stylobate Building Elevator", type:"key", note:"Requires key", pct:{x:0.61,y:0.27}, requireItems:["Stylobate key"]},
    {name:"Primorsky Ave Taxi V-Ex",type:"pay",    note:"Pay roubles for taxi extraction", pct:{x:0.54,y:0.91}, requireItems:["Roubles"]},
    {name:"Klimov Street (Flare)",  type:"special",note:"Requires flare signal", pct:{x:0.97,y:0.41}, requireItems:["Flare"]},
    {name:"Pinewood Basement (Co-Op)", type:"coop", note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
   scavExtracts:[
    {name:"Entrance to Catacombs",  type:"open",   note:"Always available — underground entrance", pct:{x:0.95,y:0.65}, requireItems:[]},
    {name:"Ventilation Shaft",      type:"open",   note:"Always available", pct:{x:0.74,y:0.87}, requireItems:[]},
    {name:"Sewer Manhole",          type:"open",   note:"Always available — sewer access", pct:{x:0.08,y:0.77}, requireItems:[]},
    {name:"Near Kamchatskaya Arch", type:"open",   note:"Always available — near the arch", pct:{x:0.11,y:0.42}, requireItems:[]},
    {name:"Cardinal Apartment Complex Parking", type:"open", note:"Always available — parking area", pct:{x:0.36,y:0.16}, requireItems:[]},
    {name:"Klimov Shopping Mall Exfil", type:"open", note:"Always available — mall area", pct:{x:0.81,y:0.35}, requireItems:[]},
   ],
  },
  {id:"ground-zero",name:"Ground Zero",tier:"Beginner",diff:1,color:"#6a8a5a",
   desc:"Starter map. Learn the basics here.",bosses:["Kollontay (roaming, rare)"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/Ground_Zero",mapgenie:"https://mapgenie.io/tarkov/maps/ground-zero",tarkovdev:"https://tarkov.dev/map/ground-zero",
   lootPoints:[
    {name:"Office Building",type:"mixed",pct:{x:0.45,y:0.35},note:"PCs, safes, office loot",tags:["Electronics","Jewelry","Money","Info"]},
    {name:"Supermarket",type:"mixed",pct:{x:0.55,y:0.5},note:"Food, barter items, medical supplies",tags:["Food","Barter item","Meds","Medical supplies"]},
    {name:"Parking Garage",type:"stash",pct:{x:0.4,y:0.6},note:"Weapon crates, duffle bags",tags:["Weapon","Barter item","Building material"]},
    {name:"Residential Buildings",type:"stash",pct:{x:0.6,y:0.4},note:"Jackets, stashes, loose loot",tags:["Key","Barter item","Food","Building material"]},
   ],
   pmcExtracts:[
    {name:"Police Cordon V-Ex",       type:"pay",    note:"Pay roubles", pct:{x:0.77,y:0.49}, requireItems:["Roubles"]},
    {name:"Tartowers Sales Office",   type:"open",   note:"Always available", pct:{x:0.17,y:0.53}, requireItems:[]},
    {name:"Emercom Checkpoint",       type:"open",   note:"Always available", pct:{x:0.28,y:0.05}, requireItems:[]},
    {name:"Nakatani Basement Stairs", type:"open",   note:"Always available", pct:{x:0.76,y:0.94}, requireItems:[]},
    {name:"Mira Ave (Flare)",         type:"special",note:"Requires flare", pct:{x:0.09,y:0.18}, requireItems:["Flare"]},
    {name:"Scav Checkpoint (Co-op)",  type:"coop",   note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
   scavExtracts:[
    {name:"Emercom Checkpoint",       type:"open",   note:"Always available", pct:{x:0.28,y:0.05}, requireItems:[]},
    {name:"Nakatani Basement Stairs", type:"open",   note:"Always available", pct:{x:0.76,y:0.94}, requireItems:[]},
    {name:"Scav Checkpoint (Co-op)",  type:"coop",   note:"NOT usable in PvE", pct:null, requireItems:[]},
   ],
  },
  {id:"the-lab",name:"The Lab",tier:"Endgame",diff:5,color:"#4a8a8a",
   desc:"Raiders everywhere. Keycards to extract.",bosses:["Raiders (entire map)","Facility Guards"],
   wiki:"https://escapefromtarkov.fandom.com/wiki/The_Lab",mapgenie:"https://mapgenie.io/tarkov/maps/the-lab",tarkovdev:"https://tarkov.dev/map/the-lab",
   lootPoints:[
    {name:"Server Room",type:"tech",pct:{x:0.45,y:0.35},note:"GPUs, electronics, server racks — premium tech",tags:["Electronics","Info"]},
    {name:"Manager's Office",type:"high-value",pct:{x:0.52,y:0.45},note:"Safe, intel, rare spawns",tags:["Jewelry","Money","Info","Key"]},
    {name:"Weapon Testing",type:"mixed",pct:{x:0.65,y:0.55},note:"Weapon crates, rare attachments, ammo",tags:["Weapon","Weapon mod","Ammo"]},
    {name:"Green Lab",type:"medical",pct:{x:0.35,y:0.6},note:"LEDX chance, stims, medical supplies",tags:["Medical supplies","Stimulant","Meds"]},
    {name:"Blue Lab",type:"tech",pct:{x:0.7,y:0.4},note:"Tech spawns, electronics, lab equipment",tags:["Electronics","Info","Barter item"]},
   ],
   pmcExtracts:[
    {name:"Hangar Gate",        type:"key",    note:"Requires keycard", pct:{x:0.81,y:0.56}, requireItems:["Keycard"]},
    {name:"Parking Gate",       type:"key",    note:"Requires keycard", pct:{x:0.15,y:0.27}, requireItems:["Keycard"]},
    {name:"Sewage Conduit",     type:"open",   note:"Always available — no backpack", pct:{x:0.77,y:0.79}, requireItems:[]},
    {name:"Ventilation Shaft",  type:"open",   note:"Always available", pct:{x:0.28,y:0.69}, requireItems:[]},
    {name:"Cargo Elevator",     type:"open",   note:"Always available", pct:{x:0.24,y:0.84}, requireItems:[]},
    {name:"Main Elevator",      type:"open",   note:"Always available", pct:{x:0.50,y:0.02}, requireItems:[]},
    {name:"Medical Block Elevator", type:"open", note:"Always available", pct:{x:0.47,y:0.84}, requireItems:[]},
   ],
   scavExtracts:[],
  },
];

// ─── MAP COORDINATE BOUNDS ──────────────────────────────────────────────
// Derived from tarkov.dev maps.json transform + coordinateRotation data.
// SVG maps are drawn inverted; these bounds map game world coords → SVG 0-1 pct.
// {left,right,top,bottom} = game coordinate value at each SVG edge.
// swap: true if axes are swapped (90°/270° rotation maps).
export const MAP_BOUNDS = {
  customs:             {left:698,right:-372,top:-307,bottom:237},
  factory:             {left:67.4,right:-64.5,top:77,bottom:-65.5,swap:true},
  woods:               {left:646,right:-761,top:-914,bottom:442},
  interchange:         {left:598,right:-433,top:-442,bottom:426},
  shoreline:           {left:504,right:-1056,top:-415,bottom:618},
  reserve:             {left:289,right:-303,top:-293,bottom:244},
  lighthouse:          {left:515,right:-545,top:-998,bottom:725},
  "streets-of-tarkov": {left:323,right:-280,top:-295,bottom:532},
  "the-lab":           {left:-477,right:-193,top:-287,bottom:-80,swap:true},
  "ground-zero":       {left:249,right:-99,top:-124,bottom:364},
};

// ─── EXTRACT POSITION MERGE ──────────────────────────────────
export function mergeExtractPositions(emapEntry, apiMap) {
  if (!emapEntry || !apiMap?.extracts?.length) return emapEntry;
  const bounds = MAP_BOUNDS[emapEntry.id];
  if (!bounds) return emapEntry;
  const apiByName = {};
  apiMap.extracts.forEach(e => { if (e.position) apiByName[e.name] = e; });
  const updateExtracts = (list) => list.map(ext => {
    const api = apiByName[ext.name];
    if (api?.position) {
      const pct = worldToPct(api.position, bounds);
      if (pct) return { ...ext, pct };
    }
    return ext;
  });
  return { ...emapEntry, pmcExtracts: updateExtracts(emapEntry.pmcExtracts || []), scavExtracts: updateExtracts(emapEntry.scavExtracts || []) };
}

export const MAP_SVG_NAMES = {customs:"Customs",factory:"Factory",woods:"Woods",interchange:"Interchange",shoreline:"Shoreline",reserve:"Reserve",lighthouse:"Lighthouse","streets-of-tarkov":"StreetsOfTarkov","the-lab":"Labs","ground-zero":"GroundZero"};
export const LAYER_DEFS = [
  { id: "route", label: "Route", icon: "━", default: true },
  { id: "bosses", label: "Bosses", icon: "☠", default: true },
  { id: "hazards", label: "Hazards", icon: "⚠", default: false },
  { id: "stashes", label: "Stashes", icon: "◉", default: false },
  { id: "locks", label: "Locks", icon: "⚿", default: false },
  { id: "btr", label: "BTR", icon: "▣", default: false },
];
