import { API_URL } from './constants.js';

// ─── GraphQL Queries ─────────────────────────────────────────
export const MAPS_Q=`{maps{id name normalizedName lootContainers{lootContainer{name} position{x y z}} bosses{boss{name} spawnChance spawnLocations{name chance} escorts{boss{name} amount{count}} spawnTime spawnTimeRandom spawnTrigger} hazards{hazardType position{x y z} outline{x y z}} locks{lockType key{name} needsPower position{x y z}} btrStops{name x y z} extracts{name faction position{x y z} switches{name}} transits{description map{normalizedName name}}}}`;
export const TASKS_Q=`{tasks(lang:en){id name wikiLink minPlayerLevel trader{name} map{id name normalizedName} taskRequirements{task{id}status} objectives{id type description optional ...on TaskObjectiveBasic{zones{id map{id} position{x y z}}} ...on TaskObjectiveMark{markerItem{name} zones{id map{id} position{x y z}}} ...on TaskObjectiveQuestItem{questItem{name} count possibleLocations{map{id} positions{x y z}} zones{id map{id} position{x y z}}} ...on TaskObjectiveShoot{targetNames count zoneNames zones{id map{id} position{x y z}}} ...on TaskObjectiveItem{items{name} count foundInRaid zones{id map{id} position{x y z}}} ...on TaskObjectiveExtract{exitName} ...on TaskObjectiveBuildItem{item{name} attributes{name requirement{value}}} ...on TaskObjectiveSkill{skillLevel{name level}} ...on TaskObjectiveTraderLevel{trader{name} level} ...on TaskObjectiveUseItem{useAny{name} count zoneNames zones{id map{id} position{x y z}}} ...on TaskObjectiveTaskStatus{task{name} status} ...on TaskObjectiveTraderStanding{trader{name} value compareMethod} ...on TaskObjectiveExperience{count} ...on TaskObjectivePlayerLevel{playerLevel}}}}`;
export const HIDEOUT_Q=`{hideoutStations{id name normalizedName levels{level itemRequirements{item{id name shortName} count} stationLevelRequirements{station{id name} level} traderRequirements{trader{name} level}}}}`;
export const TRADERS_Q=`{traders{id name imageLink}}`;

// ─── Weapons Query Builders ──────────────────────────────────
export const WEAPONS_LIST_Q = `{ items(types: [gun]) { id name shortName gridImageLink weight properties { ... on ItemPropertiesWeapon { caliber ergonomics recoilVertical recoilHorizontal fireRate fireModes } } } }`;
export const PRICE_FRAG = `buyFor { price priceRUB currency vendor { ... on TraderOffer { name minTraderLevel } ... on FleaMarket { name } } }`;
export const MOD_PROPS = `... on ItemPropertiesWeaponMod { ergonomics recoilModifier accuracyModifier } ... on ItemPropertiesScope { ergonomics recoilModifier zoomLevels sightingRange sightModes } ... on ItemPropertiesMagazine { ergonomics recoilModifier capacity loadModifier ammoCheckModifier malfunctionChance } ... on ItemPropertiesBarrel { ergonomics recoilModifier centerOfImpact deviationCurve deviationMax }`;
export const MOD_FIELDS_L3 = `id name shortName iconLink gridImageLink weight velocity loudness ${PRICE_FRAG} properties { ${MOD_PROPS} }`;
export const SLOT_FRAG = (inner) => `slots { id name nameId required filters { allowedItems { ${inner} } } }`;
export const MOD_PROPS_WITH_SLOTS = (inner) => `... on ItemPropertiesWeaponMod { ergonomics recoilModifier accuracyModifier ${SLOT_FRAG(inner)} } ... on ItemPropertiesScope { ergonomics recoilModifier zoomLevels sightingRange sightModes ${SLOT_FRAG(inner)} } ... on ItemPropertiesMagazine { ergonomics recoilModifier capacity loadModifier ammoCheckModifier malfunctionChance ${SLOT_FRAG(inner)} } ... on ItemPropertiesBarrel { ergonomics recoilModifier centerOfImpact deviationCurve deviationMax ${SLOT_FRAG(inner)} }`;
export const MOD_FIELDS_L2 = `id name shortName iconLink gridImageLink weight velocity loudness ${PRICE_FRAG} properties { ${MOD_PROPS_WITH_SLOTS(MOD_FIELDS_L3)} }`;
export const MOD_FIELDS_L1 = `id name shortName iconLink gridImageLink weight velocity loudness ${PRICE_FRAG} properties { ${MOD_PROPS_WITH_SLOTS(MOD_FIELDS_L2)} }`;
export const weaponDetailQ = (id, gameMode = "pve") => `{ item(id: "${id}", gameMode: ${gameMode}) { id name shortName image512pxLink gridImageLink weight velocity loudness ${PRICE_FRAG} properties { ... on ItemPropertiesWeapon { caliber ergonomics recoilVertical recoilHorizontal fireRate fireModes effectiveDistance maxDurability centerOfImpact convergence recoilDispersion cameraRecoil sightingRange defaultAmmo { name shortName } slots { id name nameId required filters { allowedItems { ${MOD_FIELDS_L1} } } } } } } }`;

export const ITEMS_SEARCH_Q = (term) => `{items(name:"${term.replace(/["\\\n\r]/g,"")}", limit:20){id name shortName types categories{name}}}`;

// ─── fetchAPI ───
export async function fetchAPI(q){const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q})});return(await r.json()).data;}
